// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/category.proto

package category

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Category service

func NewCategoryEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Category service

type CategoryService interface {
	CreateCategory(ctx context.Context, in *Create_Category_Request, opts ...client.CallOption) (*Create_Category_Response, error)
	UpdateCategory(ctx context.Context, in *Create_Category_Request, opts ...client.CallOption) (*Update_Category_Response, error)
	DeleteCategory(ctx context.Context, in *Delete_Category_Request, opts ...client.CallOption) (*Delete_Category_Response, error)
	FindCategoryByName(ctx context.Context, in *Find_CategoryByName_Request, opts ...client.CallOption) (*Category_Response, error)
	FindCategoryById(ctx context.Context, in *FindCateGoryById_Request, opts ...client.CallOption) (*Category_Response, error)
	FindCategoryByLevel(ctx context.Context, in *Find_CategoryByLevel_Request, opts ...client.CallOption) (*Category_Response, error)
	FindAllCategory(ctx context.Context, in *Find_All_Request, opts ...client.CallOption) (*Find_All_Response, error)
}

type categoryService struct {
	c    client.Client
	name string
}

func NewCategoryService(name string, c client.Client) CategoryService {
	return &categoryService{
		c:    c,
		name: name,
	}
}

func (c *categoryService) CreateCategory(ctx context.Context, in *Create_Category_Request, opts ...client.CallOption) (*Create_Category_Response, error) {
	req := c.c.NewRequest(c.name, "Category.CreateCategory", in)
	out := new(Create_Category_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) UpdateCategory(ctx context.Context, in *Create_Category_Request, opts ...client.CallOption) (*Update_Category_Response, error) {
	req := c.c.NewRequest(c.name, "Category.UpdateCategory", in)
	out := new(Update_Category_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) DeleteCategory(ctx context.Context, in *Delete_Category_Request, opts ...client.CallOption) (*Delete_Category_Response, error) {
	req := c.c.NewRequest(c.name, "Category.DeleteCategory", in)
	out := new(Delete_Category_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryByName(ctx context.Context, in *Find_CategoryByName_Request, opts ...client.CallOption) (*Category_Response, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryByName", in)
	out := new(Category_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryById(ctx context.Context, in *FindCateGoryById_Request, opts ...client.CallOption) (*Category_Response, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryById", in)
	out := new(Category_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindCategoryByLevel(ctx context.Context, in *Find_CategoryByLevel_Request, opts ...client.CallOption) (*Category_Response, error) {
	req := c.c.NewRequest(c.name, "Category.FindCategoryByLevel", in)
	out := new(Category_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryService) FindAllCategory(ctx context.Context, in *Find_All_Request, opts ...client.CallOption) (*Find_All_Response, error) {
	req := c.c.NewRequest(c.name, "Category.FindAllCategory", in)
	out := new(Find_All_Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Category service

type CategoryHandler interface {
	CreateCategory(context.Context, *Create_Category_Request, *Create_Category_Response) error
	UpdateCategory(context.Context, *Create_Category_Request, *Update_Category_Response) error
	DeleteCategory(context.Context, *Delete_Category_Request, *Delete_Category_Response) error
	FindCategoryByName(context.Context, *Find_CategoryByName_Request, *Category_Response) error
	FindCategoryById(context.Context, *FindCateGoryById_Request, *Category_Response) error
	FindCategoryByLevel(context.Context, *Find_CategoryByLevel_Request, *Category_Response) error
	FindAllCategory(context.Context, *Find_All_Request, *Find_All_Response) error
}

func RegisterCategoryHandler(s server.Server, hdlr CategoryHandler, opts ...server.HandlerOption) error {
	type category interface {
		CreateCategory(ctx context.Context, in *Create_Category_Request, out *Create_Category_Response) error
		UpdateCategory(ctx context.Context, in *Create_Category_Request, out *Update_Category_Response) error
		DeleteCategory(ctx context.Context, in *Delete_Category_Request, out *Delete_Category_Response) error
		FindCategoryByName(ctx context.Context, in *Find_CategoryByName_Request, out *Category_Response) error
		FindCategoryById(ctx context.Context, in *FindCateGoryById_Request, out *Category_Response) error
		FindCategoryByLevel(ctx context.Context, in *Find_CategoryByLevel_Request, out *Category_Response) error
		FindAllCategory(ctx context.Context, in *Find_All_Request, out *Find_All_Response) error
	}
	type Category struct {
		category
	}
	h := &categoryHandler{hdlr}
	return s.Handle(s.NewHandler(&Category{h}, opts...))
}

type categoryHandler struct {
	CategoryHandler
}

func (h *categoryHandler) CreateCategory(ctx context.Context, in *Create_Category_Request, out *Create_Category_Response) error {
	return h.CategoryHandler.CreateCategory(ctx, in, out)
}

func (h *categoryHandler) UpdateCategory(ctx context.Context, in *Create_Category_Request, out *Update_Category_Response) error {
	return h.CategoryHandler.UpdateCategory(ctx, in, out)
}

func (h *categoryHandler) DeleteCategory(ctx context.Context, in *Delete_Category_Request, out *Delete_Category_Response) error {
	return h.CategoryHandler.DeleteCategory(ctx, in, out)
}

func (h *categoryHandler) FindCategoryByName(ctx context.Context, in *Find_CategoryByName_Request, out *Category_Response) error {
	return h.CategoryHandler.FindCategoryByName(ctx, in, out)
}

func (h *categoryHandler) FindCategoryById(ctx context.Context, in *FindCateGoryById_Request, out *Category_Response) error {
	return h.CategoryHandler.FindCategoryById(ctx, in, out)
}

func (h *categoryHandler) FindCategoryByLevel(ctx context.Context, in *Find_CategoryByLevel_Request, out *Category_Response) error {
	return h.CategoryHandler.FindCategoryByLevel(ctx, in, out)
}

func (h *categoryHandler) FindAllCategory(ctx context.Context, in *Find_All_Request, out *Find_All_Response) error {
	return h.CategoryHandler.FindAllCategory(ctx, in, out)
}
